services:
  - type: web
    name: photobooth
    env: bun
    rootDir: vite-express-project
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: photobooth-disk
      mountPath: /opt/render/project/src/vite-express-project/public/photos
      sizeGB: 1

